[package]
name = "kernel-space"
version = "0.1.0"
edition = "2021"

[dependencies]
microkernel = { path = "../microkernel" }
control-plane = { path = "../control-plane" }
kernel = { path = "../kernel" }
inventory = "0.3.15"
serde_json = "1.0.128"
